[package]
name = "devplexer"
version = "0.1.0"
edition = "2024"

[dependencies]
osakit = { version = "0.3.1", features = ["full"] }
tmux_interface = { version = "0.3.2" }
sysinfo = { version = "0.37.0" }
