[package]
name = "devplexer"
version = "0.1.0"
edition = "2024"

[dependencies]
osakit = { version = "0.3.1", features = ["full"] }
tmux_interface = { version = "0.3.2" }
sysinfo = { version = "0.37.0" }
yaml-rust2 = { version = "0.10.4" }
ratatui = {version = "0.29.0"}
